### ISSUE TITLE
issues with the project component.

### ISSUE THREAD

**Issue by Boby900** [Boby900/front-website#1]
- I want the project section to be aligned in the middle and project images are also not aligned with the text,
- your suggestions will be highly appreciated
![Screenshot (20)](https://user-images.githubusercontent.com/111265239/210290226-50665ad1-a9c1-4ee6-b7fd-23c342d1327d.png)

**Comment by arimasfinest** [comment]
Hey @Boby900, is it okay if i work on this?

**Comment by MostlyGenius** [comment]
I'd like to solve the issue, please assign it to me. I am super genius and will fix your page so it is the envy of all your enemy's
@Boby900,

**Comment by Boby900** [comment]
thanks @Tizsic 
thanks @MostlyGenius my issue has resolved now
